### ISSUE TITLE
psci/arguments is actually comint startfile followed by arguments

### ISSUE THREAD

**Issue by reuben364** [ardumont/emacs-psci#11]
The function `psci` makes a comint buffer with this:
` (apply 'make-comint-in-buffer psci/buffer-name buffer
                 psci-program psci/arguments)`

https://github.com/ardumont/emacs-psci/blob/master/psci.el#L165-L166

But the signature of `make-comint-in-buffer` is `(name buffer program &optional startfile &rest switches)`.

So the head of psci/arguments is the startfile and the tail is the arguments.

**Comment by ardumont** [comment]
So the change would be:

```
(apply 'make-comint-in-buffer psci/buffer-name buffer psci-program nil psci/arguments)
```

is that what you're implying?

Cheers,

**Comment by reuben364** [comment]
Yes.

**Comment by ardumont** [comment]
> Yes.

Ack.
I've fixed it but i can't test that it still works.

Do you please have some easy steps to help me bootstrap a small purescript env?
Mine is completely obsolete since i did not touch any of it for a long time.

**Comment by bsermons** [comment]
This was also fixed in the PR I submitted.

**Comment by ardumont** [comment]
@bsermons ack and thx again ^^
Will take a look now that i can see the diffs ^^

**Comment by ardumont** [comment]
The PR in question was merged.

Thanks for raising this up!
