### ISSUE TITLE
psci/--project-root!: Wrong type argument: stringp, nil [3 times] on launch

### ISSUE THREAD

**Issue by dimashenme** [ardumont/emacs-psci#12]
Hi,

I am using the latest (d773b407f772e6ab3c40406c22824889e0fd14fe)
 snapshot of psci.el

Whenever I do M-x psci I get this error message

psci/--project-root!: Wrong type argument: stringp, nil [3 times]

It happens even if there is .psci file in the current directory. The function (psci/--project-root!)
does return the current directory if evaluated with purescript source buffer as a current buffer
but breaks down if it is dired for example. Still, it doesn't matter whether I call psci from a purescript
buffer or from any other buffer --- I still have this error message above.

**Comment by dimashenme** [comment]
the problem turned out to be due to psci.el's implicit dependence on the "projectile" package. intalling "projectile" resolves the issue.

**Comment by ardumont** [comment]
> the problem turned out to be due to psci.el's implicit dependence on the "projectile" package.

And no dependency should be implicit!
Thanks for the heads up!

Cheers,
