### ISSUE TITLE
`M-x psci` errors if there is no .psci file.

### ISSUE THREAD

**Issue by sellout** [ardumont/emacs-psci#3]
In a PureScript buffer, I run `M-x psci` and an empty “*psci*” buffer opens. Then the entry “psci/--project-root!: Wrong type argument: stringp, nil” is added to “*Messages*”. `debug-on-error` is enabled, but I don’t end up in the debugger for some reason.

It looks like `psci/--project-root!` doesn’t try to do anything (even report a better error, like “need a .psci file”) if `locate-dominating-file` returns `nil`.

**Comment by ardumont** [comment]
Yes, it's a dummy wrapper.
Will look into it.

Thanks for the reminder.
