### ISSUE TITLE
Need better regex for `psci/--compute-module-name!`

### ISSUE THREAD

**Issue by sellout** [ardumont/emacs-psci#4]
The current regex requires a space after the module name, but I have Emacs clean up all trailing whitespace, so it can never find the module. I think `"^module\\s-+\\\([a-zA-Z0-9\\\.]+\\\)\\b"` (using word boundary rather than a space) will do the right thing. I also replace the space after “module” with `\\s-+` to allow for arbitrary whitespace.

**Comment by ardumont** [comment]
Hello,

Thanks for the heads up!

Cheers,
