### ISSUE TITLE
strange keybinding

### ISSUE THREAD

**Issue by nrolland** [ardumont/emacs-psci#7]
For some reason after pressing Enter in any purescript file, it makes me jump to another buffer saying 

```
purescript-mode-hook is a variable defined in `purescript-mode.el'.
Its value is nil

  This variable may be risky if used as a file-local variable.

Documentation:
Hook run after entering PureScript mode.
No problems result if this variable is not bound.
`add-hook' automatically binds it.  (This is true for all hook variables.)

You can customize this variable.

[back]
```

I guess its not linked to emacs-psci though, but to my purescript mode conf..

**Comment by nrolland** [comment]
Nothing to do with it, for some reason I can see C-h k   <RET> boing bound to help-follow for god knows why..

**Comment by ardumont** [comment]
Hello,

I do not get it either.
But for information, psci-mode do have a dependency on purescript-mode for its font.

Cheers,

**Comment by eallik** [comment]
I'm having this issue — I just installed `purescript-mode`, and for example when I press tab, it always pops up.
