### ISSUE TITLE
Sending commands to psci causes the process to quit

### ISSUE THREAD

**Issue by bsermons** [ardumont/emacs-psci#9]
Using 0.7.5.3 of purescript/psci, anything that calls the psci/--run-psci-command! function causes the psci process to quit.  

I think it is the call to process-send-eof that is causing it since manually sending EOF has the same behavior.

**Comment by ardumont** [comment]
Hello,

you can test your assertion by monkey-patching this function from:

```lisp
(defun psci/--run-psci-command! (command)
  "Run psci COMMAND as string."
  (-when-let (process (get-buffer-process (psci/--process-name psci/buffer-name)))
    (comint-simple-send process command)
    (process-send-eof process)))

```

to:
```lisp
(defun psci/--run-psci-command! (command)
  "Run psci COMMAND as string."
  (-when-let (process (get-buffer-process (psci/--process-name psci/buffer-name)))
    (comint-simple-send process command)))
```
(not tested)

Use a *scratch* buffer, copy the second definition and eval it (M-x eval-buffer).

Then try again what you actually did to have the problem.
Is it better?

Note: 
- I did not tested it.
- This is volatile and only for test purposes. As soon as you will restart your emacs, those changes will be lost. To get back to the normal definition without restarting emacs, eval the first definition.

Cheers,

**Comment by bsermons** [comment]
Taking out the process-send-eof call fixes this issue. However, it seems that the format of the .psci file has changed so other commands such as psci/load-project-modules! no longer works.  I'm a complete beginner with purescript but I'll try and play around with it this week and see if I can fix some of the problems I'm seeing before I do a PR.

**Comment by ardumont** [comment]
Hello,

> Taking out the process-send-eof call fixes this issue. 

ok.

>  However, it seems that the format of the .psci file has changed so other commands such as psci/load-project-modules! no longer works.

I admit it's been a long time since i tried to do some purescript so i'm not up to date.
I even tried to reload my ardumont/purescript-lab to check your assertion and failed (for now).

> I'm a complete beginner with purescript but I'll try and play around with it this week and see if I can fix some of the problems I'm seeing before I do a PR.

Ok, thanks for your time.

Cheers,

**Comment by bsermons** [comment]
This should be fixed with the latest PR.  Thanks!

**Comment by ardumont** [comment]
> This should be fixed with the latest PR. Thanks!

Well, thank you really ^^
